services:
  postgres:
    image: postgres:13
    container_name: financas_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: financas
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - financas_network
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: financas_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - financas_network
    restart: always

  node:
    build: ./app
    container_name: financas_node
    env_file:
      - ./app/.env
    volumes:
      - ./app:/usr/src/app:delegated
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - financas_network
    depends_on:
      - postgres
    restart: always

  nginx:
    image: nginx:latest
    container_name: financas_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app:/usr/src/app:ro
    ports:
      - "80:80"
    networks:
      - financas_network
    depends_on:
      - node
    restart: always

networks:
  financas_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
