CREATE TABLE IF NOT EXISTS usuarios (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    senha VARCHAR(255) NOT NULL,
    dt_cad TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    dt_upd TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
); 